# Generated by Django 4.0.5 on 2022-07-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=5000)),
                ('tags', models.ManyToManyField(to='Home.tags')),
            ],
        ),
    ]
