# Generated by Django 4.0.5 on 2022-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
