# Generated by Django 4.0.5 on 2022-08-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
